# Generated by Django 3.0.2 on 2020-02-04 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='newone',
            field=models.IntegerField(default=0),
        ),
    ]
